#!/bin/sh
echo "OMP_NUM_THREADS = $OMP_NUM_THREADS"
echo
for SCHEDULE_TYPE in static dynamic guided
do
echo "$SCHEDULE_TYPE"
echo
for CHUNK in 1 2 5 8 10 20 50 80 100 200 500 800 1000
do
echo -ne "$CHUNK\t"
export OMP_SCHEDULE="$SCHEDULE_TYPE, $CHUNK"
./main
done
done